# Get the json file, and its corresponding label files

In [187]:
# All imports
import os
import json
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split

Identify files that have their labels as well, print out the ones that don't have their corresponding label files

In [14]:
i = 0
list_of_files = []
for f in os.listdir("./AGjsons/"):
    if os.path.isfile("./labels/" + str(f)):
        list_of_files.append(f)
#         print f, "exists along with its label file"
        i += 1
    else:
        print f
print "\n", i, "is the number of files with their label files"

ERS915177.json
ERS915179.json
ERS915178.json
ERS915518.json

1122 is the number of files with their label files


Through each file, extract the contents and update the matrix X and Y. Matrix X has the data of each file laid out in rows

In [168]:
taxons = None
X = []
Y = []

i = 0
for f in list_of_files:
    print f
    x_dic = json.loads(open("./AGjsons/" + f).read())
    
    # Just one time, read all the taxons
    if i == 0:
        taxons = sorted(x_dic.keys())
    
    # Append X to have the data
    X.append([x_dic[k] for k in taxons])
    
    y_dic = json.loads(open("./labels/" + f).read())
    
    # Append Y to have the label for that file
    if y_dic['sex'] == "female":
        Y.append(1)
    else:
        Y.append(0)



ERS915203.json
ERS914941.json
ERS915653.json
ERS915346.json
ERS914804.json
ERS915716.json
ERS915595.json
ERS915080.json
ERS915829.json
ERS914916.json
ERS915604.json
ERS915254.json
ERS914853.json
ERS915741.json
ERS915311.json
ERS915038.json
ERS915468.json
ERS915192.json
ERS914783.json
ERS915487.json
ERS915242.json
ERS915612.json
ERS914900.json
ERS915307.json
ERS915757.json
ERS914845.json
ERS914795.json
ERS915184.json
ERS915491.json
ERS915868.json
ERS915645.json
ERS914957.json
ERS915215.json
ERS915700.json
ERS914812.json
ERS915350.json
ERS915079.json
ERS915583.json
ERS915429.json
ERS915096.json
ERS914869.json
ERS915281.json
ERS915794.json
ERS914886.json
ERS915844.json
ERS914756.json
ERS915147.json
ERS915517.json
ERS915002.json
ERS915452.json
ERS915686.json
ERS914994.json
ERS915239.json
ERS915669.json
ERS915393.json
ERS915540.json
ERS915110.json
ERS915813.json
ERS915405.json
ERS915055.json
ERS914828.json
ERS914982.json
ERS915690.json
ERS915385.json
ERS915805.json
ERS915106.json
ERS915556.

ERS915440.json
ERS915010.json
ERS915505.json
ERS915155.json
ERS915856.json
ERS914744.json
ERS915786.json
ERS914894.json
ERS915339.json
ERS915293.json
ERS915047.json
ERS915417.json
ERS915801.json
ERS915102.json
ERS915552.json
ERS914969.json
ERS915381.json
ERS915694.json
ERS914986.json
ERS915401.json
ERS915051.json
ERS915544.json
ERS915114.json
ERS915817.json
ERS915397.json
ERS915378.json
ERS914990.json
ERS915682.json
ERS915728.json
ERS915006.json
ERS915456.json
ERS914752.json
ERS915840.json
ERS915143.json
ERS915513.json
ERS914928.json
ERS914882.json
ERS915790.json
ERS915285.json
ERS915138.json
ERS915568.json
ERS915092.json
ERS915587.json
ERS914816.json
ERS915704.json
ERS915354.json
ERS914953.json
ERS915641.json
ERS915211.json
ERS915495.json
ERS914791.json
ERS915180.json
ERS915303.json
ERS914841.json
ERS915753.json
ERS915246.json
ERS914904.json
ERS915616.json
ERS914768.json
ERS915483.json
ERS915529.json
ERS915196.json
ERS914787.json
ERS915745.json
ERS914857.json
ERS915315.json
ERS915600.

In [169]:
X = np.array(X)
Y = np.array(Y)

# To confirm the lengths of the data
print np.shape(X)
print len(Y)

(1122, 983)
1122


In [170]:
# Check X
X[0, :]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,   48,    0,    0,    9,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

## Filter the data by deleting taxons that have a variance which lies outside a range

In [171]:
# Set the range for the tolerance on variances
range_low = 50
range_high = 150

Go through every column of the data, get the variance. If the variance is out of range, remove that column

In [172]:
tmp_X = X
taxons_to_keep = []
cols_to_keep = []
for i in range(np.shape(tmp_X)[1]):
    var = np.var(tmp_X[:, i])
    if var > range_low and var < range_high:
        taxons_to_keep.append(taxons[i])
        cols_to_keep.append(i)
#     print "col", i, "= ", var

### The taxons that passed our variance test

In [181]:
print taxons_to_keep

[u'106589', u'131110', u'1541959', u'1663', u'1703', u'1707785', u'187101', u'187491', u'1911587', u'1913578', u'2033435', u'2053', u'2132', u'327575', u'43668', u'539', u'712368', u'797277', u'838', u'84567', u'85413', u'856', u'879274', u'941907']


### New X generated after only keeping the taxons that passed our test

In [185]:
new_X = np.ones((np.shape(X)[0], len(taxons_to_keep)))
print np.shape(new_X)
for i in range(len(cols_to_keep)):
    new_X[:, i] = X[:, cols_to_keep[i]]
    
print new_X
print len(Y)

(1122, 24)
[[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ... 56.  0.  0.]
 [ 0.  5.  0. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]
1122


# Run the neural net on the processed data

In [218]:
X_train, X_test, y_train, y_test = train_test_split(new_X, Y, test_size=0.20, shuffle=False)

# Specify feature
feature_columns = [tf.feature_column.numeric_column("x", shape=[np.shape(X_train)[1]])]

In [223]:
# Build 2 layer DNN classifier
# classifier = tf.estimator.DNNClassifier(
#     feature_columns=feature_columns,
#     hidden_units=[20, 5],
#     optimizer=tf.train.ProximalAdagradOptimizer(
#       learning_rate=0.1,
#       l1_regularization_strength=0.001
#     ),
#     n_classes=2,
#     dropout=0.5,
#     model_dir="./tmp/mnist_model"
# )

classifier = tf.estimator.DNNClassifier(feature_columns=feature_columns, hidden_units=[50,50],n_classes=2, dropout=0.5, optimizer=tf.train.ProximalAdagradOptimizer(
      learning_rate=0.1,
      l1_regularization_strength=0.001
    ), batch_norm=True)

# Define the training inputs
train_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"x": X_train},
    y=y_train,
    num_epochs=None,
    batch_size=128,
    shuffle=True
)

classifier.train(input_fn=train_input_fn, steps=100000)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_save_checkpoints_secs': 600, '_num_ps_replicas': 0, '_keep_checkpoint_max': 5, '_task_type': 'worker', '_global_id_in_cluster': 0, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x12b81ca90>, '_model_dir': '/var/folders/5f/657ms1d94zg0jdmhwsd0xg080000gn/T/tmpBYOpmq', '_protocol': None, '_save_checkpoints_steps': None, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_device_fn': None, '_experimental_distribute': None, '_num_worker_replicas': 1, '_task_id': 0, '_log_step_count_steps': 100, '_evaluation_master': '', '_eval_distribute': None, '_train_distribute': None, '_master': ''}
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create Checkp

INFO:tensorflow:loss = 79.30069, step = 7001 (0.167 sec)
INFO:tensorflow:global_step/sec: 646.325
INFO:tensorflow:loss = 86.07067, step = 7101 (0.154 sec)
INFO:tensorflow:global_step/sec: 642.632
INFO:tensorflow:loss = 84.47176, step = 7201 (0.156 sec)
INFO:tensorflow:global_step/sec: 568.906
INFO:tensorflow:loss = 84.122406, step = 7301 (0.177 sec)
INFO:tensorflow:global_step/sec: 566.749
INFO:tensorflow:loss = 77.16562, step = 7401 (0.176 sec)
INFO:tensorflow:global_step/sec: 609.622
INFO:tensorflow:loss = 77.43895, step = 7501 (0.164 sec)
INFO:tensorflow:global_step/sec: 555.803
INFO:tensorflow:loss = 76.85129, step = 7601 (0.180 sec)
INFO:tensorflow:global_step/sec: 576.641
INFO:tensorflow:loss = 80.55076, step = 7701 (0.173 sec)
INFO:tensorflow:global_step/sec: 623.535
INFO:tensorflow:loss = 77.98132, step = 7801 (0.161 sec)
INFO:tensorflow:global_step/sec: 619.428
INFO:tensorflow:loss = 84.688995, step = 7901 (0.161 sec)
INFO:tensorflow:global_step/sec: 585.33
INFO:tensorflow:los

INFO:tensorflow:global_step/sec: 637.784
INFO:tensorflow:loss = 78.84186, step = 15401 (0.157 sec)
INFO:tensorflow:global_step/sec: 604.548
INFO:tensorflow:loss = 79.19882, step = 15501 (0.165 sec)
INFO:tensorflow:global_step/sec: 652.588
INFO:tensorflow:loss = 87.547485, step = 15601 (0.153 sec)
INFO:tensorflow:global_step/sec: 631.964
INFO:tensorflow:loss = 78.42076, step = 15701 (0.159 sec)
INFO:tensorflow:global_step/sec: 662.936
INFO:tensorflow:loss = 76.60741, step = 15801 (0.150 sec)
INFO:tensorflow:global_step/sec: 669.932
INFO:tensorflow:loss = 82.01134, step = 15901 (0.149 sec)
INFO:tensorflow:global_step/sec: 669.657
INFO:tensorflow:loss = 75.04794, step = 16001 (0.149 sec)
INFO:tensorflow:global_step/sec: 630.613
INFO:tensorflow:loss = 75.87802, step = 16101 (0.159 sec)
INFO:tensorflow:global_step/sec: 638.202
INFO:tensorflow:loss = 73.57373, step = 16201 (0.157 sec)
INFO:tensorflow:global_step/sec: 629.719
INFO:tensorflow:loss = 74.62128, step = 16301 (0.158 sec)
INFO:tens

INFO:tensorflow:global_step/sec: 634.889
INFO:tensorflow:loss = 77.208725, step = 23701 (0.157 sec)
INFO:tensorflow:global_step/sec: 658.254
INFO:tensorflow:loss = 75.17206, step = 23801 (0.152 sec)
INFO:tensorflow:global_step/sec: 666.814
INFO:tensorflow:loss = 76.91551, step = 23901 (0.150 sec)
INFO:tensorflow:global_step/sec: 568.77
INFO:tensorflow:loss = 79.26347, step = 24001 (0.176 sec)
INFO:tensorflow:global_step/sec: 556.957
INFO:tensorflow:loss = 72.32875, step = 24101 (0.179 sec)
INFO:tensorflow:global_step/sec: 657.657
INFO:tensorflow:loss = 75.0472, step = 24201 (0.152 sec)
INFO:tensorflow:global_step/sec: 588.522
INFO:tensorflow:loss = 73.01224, step = 24301 (0.170 sec)
INFO:tensorflow:global_step/sec: 574.756
INFO:tensorflow:loss = 79.57214, step = 24401 (0.174 sec)
INFO:tensorflow:global_step/sec: 622.964
INFO:tensorflow:loss = 87.07616, step = 24501 (0.161 sec)
INFO:tensorflow:global_step/sec: 668.047
INFO:tensorflow:loss = 73.885056, step = 24601 (0.149 sec)
INFO:tenso

INFO:tensorflow:global_step/sec: 574.997
INFO:tensorflow:loss = 76.68595, step = 32001 (0.174 sec)
INFO:tensorflow:global_step/sec: 549.076
INFO:tensorflow:loss = 66.59227, step = 32101 (0.182 sec)
INFO:tensorflow:global_step/sec: 571.579
INFO:tensorflow:loss = 71.05945, step = 32201 (0.175 sec)
INFO:tensorflow:global_step/sec: 562.3
INFO:tensorflow:loss = 82.81593, step = 32301 (0.177 sec)
INFO:tensorflow:global_step/sec: 577.981
INFO:tensorflow:loss = 77.901924, step = 32401 (0.173 sec)
INFO:tensorflow:global_step/sec: 581.169
INFO:tensorflow:loss = 74.08247, step = 32501 (0.172 sec)
INFO:tensorflow:global_step/sec: 553.321
INFO:tensorflow:loss = 76.98521, step = 32601 (0.181 sec)
INFO:tensorflow:global_step/sec: 574.284
INFO:tensorflow:loss = 80.17778, step = 32701 (0.174 sec)
INFO:tensorflow:global_step/sec: 557.78
INFO:tensorflow:loss = 74.39993, step = 32801 (0.179 sec)
INFO:tensorflow:global_step/sec: 580.737
INFO:tensorflow:loss = 80.43956, step = 32901 (0.172 sec)
INFO:tensorf

INFO:tensorflow:global_step/sec: 668.784
INFO:tensorflow:loss = 74.62713, step = 40301 (0.149 sec)
INFO:tensorflow:global_step/sec: 615.192
INFO:tensorflow:loss = 78.26593, step = 40401 (0.163 sec)
INFO:tensorflow:global_step/sec: 588.634
INFO:tensorflow:loss = 75.35768, step = 40501 (0.170 sec)
INFO:tensorflow:global_step/sec: 612.771
INFO:tensorflow:loss = 71.422714, step = 40601 (0.163 sec)
INFO:tensorflow:global_step/sec: 634.581
INFO:tensorflow:loss = 73.319244, step = 40701 (0.158 sec)
INFO:tensorflow:global_step/sec: 649.179
INFO:tensorflow:loss = 77.97574, step = 40801 (0.154 sec)
INFO:tensorflow:global_step/sec: 639.942
INFO:tensorflow:loss = 78.54628, step = 40901 (0.156 sec)
INFO:tensorflow:global_step/sec: 572.895
INFO:tensorflow:loss = 79.792725, step = 41001 (0.175 sec)
INFO:tensorflow:global_step/sec: 621.23
INFO:tensorflow:loss = 71.0731, step = 41101 (0.161 sec)
INFO:tensorflow:global_step/sec: 563.066
INFO:tensorflow:loss = 72.52111, step = 41201 (0.177 sec)
INFO:tens

INFO:tensorflow:global_step/sec: 622.126
INFO:tensorflow:loss = 81.087036, step = 48601 (0.161 sec)
INFO:tensorflow:global_step/sec: 599.126
INFO:tensorflow:loss = 78.66016, step = 48701 (0.167 sec)
INFO:tensorflow:global_step/sec: 581.399
INFO:tensorflow:loss = 80.50588, step = 48801 (0.172 sec)
INFO:tensorflow:global_step/sec: 538.326
INFO:tensorflow:loss = 76.578186, step = 48901 (0.186 sec)
INFO:tensorflow:global_step/sec: 587.792
INFO:tensorflow:loss = 72.26345, step = 49001 (0.170 sec)
INFO:tensorflow:global_step/sec: 630.188
INFO:tensorflow:loss = 71.197914, step = 49101 (0.159 sec)
INFO:tensorflow:global_step/sec: 576.977
INFO:tensorflow:loss = 74.39764, step = 49201 (0.173 sec)
INFO:tensorflow:global_step/sec: 510.929
INFO:tensorflow:loss = 82.71841, step = 49301 (0.196 sec)
INFO:tensorflow:global_step/sec: 580.97
INFO:tensorflow:loss = 73.55073, step = 49401 (0.172 sec)
INFO:tensorflow:global_step/sec: 615.427
INFO:tensorflow:loss = 76.95183, step = 49501 (0.162 sec)
INFO:ten

INFO:tensorflow:global_step/sec: 626.711
INFO:tensorflow:loss = 74.152725, step = 56901 (0.160 sec)
INFO:tensorflow:global_step/sec: 638.484
INFO:tensorflow:loss = 77.82125, step = 57001 (0.157 sec)
INFO:tensorflow:global_step/sec: 584.912
INFO:tensorflow:loss = 74.54183, step = 57101 (0.171 sec)
INFO:tensorflow:global_step/sec: 607.84
INFO:tensorflow:loss = 75.01049, step = 57201 (0.165 sec)
INFO:tensorflow:global_step/sec: 631.648
INFO:tensorflow:loss = 76.778366, step = 57301 (0.158 sec)
INFO:tensorflow:global_step/sec: 637.959
INFO:tensorflow:loss = 78.50873, step = 57401 (0.157 sec)
INFO:tensorflow:global_step/sec: 522.556
INFO:tensorflow:loss = 79.416214, step = 57501 (0.191 sec)
INFO:tensorflow:global_step/sec: 564.414
INFO:tensorflow:loss = 81.1307, step = 57601 (0.178 sec)
INFO:tensorflow:global_step/sec: 537.178
INFO:tensorflow:loss = 71.671906, step = 57701 (0.186 sec)
INFO:tensorflow:global_step/sec: 553.271
INFO:tensorflow:loss = 78.62969, step = 57801 (0.181 sec)
INFO:ten

INFO:tensorflow:global_step/sec: 627.884
INFO:tensorflow:loss = 76.42894, step = 65201 (0.159 sec)
INFO:tensorflow:global_step/sec: 661.928
INFO:tensorflow:loss = 79.06729, step = 65301 (0.151 sec)
INFO:tensorflow:global_step/sec: 678.643
INFO:tensorflow:loss = 71.75185, step = 65401 (0.148 sec)
INFO:tensorflow:global_step/sec: 674.928
INFO:tensorflow:loss = 76.65802, step = 65501 (0.148 sec)
INFO:tensorflow:global_step/sec: 665.022
INFO:tensorflow:loss = 72.900925, step = 65601 (0.150 sec)
INFO:tensorflow:global_step/sec: 594.548
INFO:tensorflow:loss = 74.14, step = 65701 (0.168 sec)
INFO:tensorflow:global_step/sec: 628.35
INFO:tensorflow:loss = 69.93689, step = 65801 (0.159 sec)
INFO:tensorflow:global_step/sec: 619.073
INFO:tensorflow:loss = 72.43248, step = 65901 (0.162 sec)
INFO:tensorflow:global_step/sec: 583.567
INFO:tensorflow:loss = 73.5036, step = 66001 (0.171 sec)
INFO:tensorflow:global_step/sec: 631.038
INFO:tensorflow:loss = 79.09021, step = 66101 (0.158 sec)
INFO:tensorflo

INFO:tensorflow:global_step/sec: 571.024
INFO:tensorflow:loss = 79.06929, step = 73501 (0.175 sec)
INFO:tensorflow:global_step/sec: 557.992
INFO:tensorflow:loss = 79.882545, step = 73601 (0.180 sec)
INFO:tensorflow:global_step/sec: 533.906
INFO:tensorflow:loss = 75.8669, step = 73701 (0.187 sec)
INFO:tensorflow:global_step/sec: 562.939
INFO:tensorflow:loss = 76.001205, step = 73801 (0.178 sec)
INFO:tensorflow:global_step/sec: 570.213
INFO:tensorflow:loss = 71.813126, step = 73901 (0.176 sec)
INFO:tensorflow:global_step/sec: 605.338
INFO:tensorflow:loss = 78.62878, step = 74001 (0.165 sec)
INFO:tensorflow:global_step/sec: 577.757
INFO:tensorflow:loss = 72.68939, step = 74101 (0.173 sec)
INFO:tensorflow:global_step/sec: 583.332
INFO:tensorflow:loss = 71.4866, step = 74201 (0.171 sec)
INFO:tensorflow:global_step/sec: 523.02
INFO:tensorflow:loss = 72.84741, step = 74301 (0.192 sec)
INFO:tensorflow:global_step/sec: 568.984
INFO:tensorflow:loss = 78.638054, step = 74401 (0.175 sec)
INFO:tens

INFO:tensorflow:global_step/sec: 606.715
INFO:tensorflow:loss = 74.39768, step = 81801 (0.165 sec)
INFO:tensorflow:global_step/sec: 629.664
INFO:tensorflow:loss = 69.47782, step = 81901 (0.159 sec)
INFO:tensorflow:global_step/sec: 594.753
INFO:tensorflow:loss = 68.301506, step = 82001 (0.169 sec)
INFO:tensorflow:global_step/sec: 597.865
INFO:tensorflow:loss = 79.829605, step = 82101 (0.167 sec)
INFO:tensorflow:global_step/sec: 598.913
INFO:tensorflow:loss = 70.111176, step = 82201 (0.167 sec)
INFO:tensorflow:global_step/sec: 622.789
INFO:tensorflow:loss = 79.78615, step = 82301 (0.161 sec)
INFO:tensorflow:global_step/sec: 645.107
INFO:tensorflow:loss = 74.98378, step = 82401 (0.155 sec)
INFO:tensorflow:global_step/sec: 614.825
INFO:tensorflow:loss = 76.66598, step = 82501 (0.163 sec)
INFO:tensorflow:global_step/sec: 597.379
INFO:tensorflow:loss = 80.492615, step = 82601 (0.167 sec)
INFO:tensorflow:global_step/sec: 557.749
INFO:tensorflow:loss = 71.10663, step = 82701 (0.179 sec)
INFO:t

INFO:tensorflow:global_step/sec: 596.324
INFO:tensorflow:loss = 78.50839, step = 90101 (0.167 sec)
INFO:tensorflow:global_step/sec: 588.142
INFO:tensorflow:loss = 74.40961, step = 90201 (0.170 sec)
INFO:tensorflow:global_step/sec: 545.78
INFO:tensorflow:loss = 74.90051, step = 90301 (0.183 sec)
INFO:tensorflow:global_step/sec: 667.802
INFO:tensorflow:loss = 71.2188, step = 90401 (0.150 sec)
INFO:tensorflow:global_step/sec: 534.44
INFO:tensorflow:loss = 76.06929, step = 90501 (0.187 sec)
INFO:tensorflow:global_step/sec: 478.762
INFO:tensorflow:loss = 78.04251, step = 90601 (0.209 sec)
INFO:tensorflow:global_step/sec: 574.119
INFO:tensorflow:loss = 79.2442, step = 90701 (0.174 sec)
INFO:tensorflow:global_step/sec: 584.04
INFO:tensorflow:loss = 71.521255, step = 90801 (0.172 sec)
INFO:tensorflow:global_step/sec: 578.59
INFO:tensorflow:loss = 68.960724, step = 90901 (0.173 sec)
INFO:tensorflow:global_step/sec: 572.692
INFO:tensorflow:loss = 72.83188, step = 91001 (0.174 sec)
INFO:tensorflo

INFO:tensorflow:global_step/sec: 602.852
INFO:tensorflow:loss = 74.354935, step = 98401 (0.166 sec)
INFO:tensorflow:global_step/sec: 633.501
INFO:tensorflow:loss = 78.4292, step = 98501 (0.158 sec)
INFO:tensorflow:global_step/sec: 639.235
INFO:tensorflow:loss = 70.793, step = 98601 (0.157 sec)
INFO:tensorflow:global_step/sec: 647.345
INFO:tensorflow:loss = 76.5636, step = 98701 (0.154 sec)
INFO:tensorflow:global_step/sec: 673.564
INFO:tensorflow:loss = 70.551994, step = 98801 (0.148 sec)
INFO:tensorflow:global_step/sec: 629.501
INFO:tensorflow:loss = 74.79257, step = 98901 (0.159 sec)
INFO:tensorflow:global_step/sec: 648.277
INFO:tensorflow:loss = 73.01576, step = 99001 (0.154 sec)
INFO:tensorflow:global_step/sec: 622.58
INFO:tensorflow:loss = 71.99819, step = 99101 (0.161 sec)
INFO:tensorflow:global_step/sec: 650.961
INFO:tensorflow:loss = 77.53839, step = 99201 (0.154 sec)
INFO:tensorflow:global_step/sec: 667.575
INFO:tensorflow:loss = 76.21605, step = 99301 (0.150 sec)
INFO:tensorfl

In [224]:
# Define the test inputs
test_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"x": X_test},
    y=y_test,
    num_epochs=1,
    shuffle=False
)

# Evaluate accuracy
accuracy_score = classifier.evaluate(input_fn=test_input_fn)["accuracy"]

print("\nTest Accuracy: {0:f}%\n".format(accuracy_score*100))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-01-06-10:39:40
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/5f/657ms1d94zg0jdmhwsd0xg080000gn/T/tmpBYOpmq/model.ckpt-100000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Finished evaluation at 2019-01-06-10:39:41
INFO:tensorflow:Saving dict for global step 100000: accuracy = 0.47555557, accuracy_baseline = 0.5377778, auc = 0.5320248, auc_precision_recall = 0.76669896, average_loss = 0.6783116, global_step = 100000, label/mean = 0.5377778, loss = 76.31005, precision = 1.0, prediction/mean = 0.48103034, recall = 0.024793388
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 100000: /var/folders/5f/657ms1d94zg0jdmhwsd0xg080000gn/T/tmpBYOpmq/model.ckpt-100000

Test Accuracy: 47.555557%

